apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: spring-firestore
    manager: kube-controller-manager
    operation: Update
  name: spring-firestore
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-firestore
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-firestore
    spec:
      containers:
      - image: preethamru/mmv2-firebaseexample:0.0.2-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv2-firebaseexample
        envFrom:
          - configMapRef:
              name: firestore-url
#        env:
#         - name: CURRENCY_EXCHANGE_URI
#            value: http://currency-exchange 
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: spring-firestore
  name: spring-firestore
  namespace: default
spec:
  ports:
  - port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app: spring-firestore
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: <ingress IP>
---
apiVersion: v1
data:
  DEV_SERVICE_ACCOUNT_JSON: <service account key>
kind: ConfigMap
metadata:
  name: firestore-url
  namespace: default

